name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest,ubuntu-latest,windows-latest]
        include:
          - os: macos-latest
            python-version: 3.11
            artifact: cookiecutter-darwin
            dist: dist/cookiecutter
          - os: ubuntu-latest
            python-version: 3.11
            artifact: cookiecutter-linux
            dist: dist/cookiecutter
          - os: windows-latest
            python-version: 3.11
            artifact: cookiecutter-win
            dist: dist/cookiecutter.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: |
            .venv
          key: ${{ runner.os }}-${{ hashFiles('Pipfile*') }}

      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install -d
          pipenv run pip install altgraph

      - name: Build
        run: pipenv run build

      - name: Upload Standalone Binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.dist }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset MacOS Darwin
        id: upload-release-asset-macos-darwin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/cookiecutter-darwin/cookiecutter
          asset_name: cookiecutter-darwin
          asset_content_type: application/octet-stream

      - name: Upload Release Asset Linux
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/cookiecutter-linux/cookiecutter
          asset_name: cookiecutter-linux
          asset_content_type: application/octet-stream

      - name: Upload Release Asset Windows
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/cookiecutter-win/cookiecutter.exe
          asset_name: cookiecutter.exe
          asset_content_type: application/octet-stream